/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vitor
 */
public class CadastrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    public CadastrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblComple = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtComple = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Cliente");
        getContentPane().setLayout(null);

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(100, 110, 60, 16);

        lblCelular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCelular.setText("Celular:");
        getContentPane().add(lblCelular);
        lblCelular.setBounds(100, 400, 80, 40);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(100, 150, 60, 40);

        lblRua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRua.setText("Rua:");
        getContentPane().add(lblRua);
        lblRua.setBounds(100, 200, 60, 40);

        lblCep.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCep.setText("CEP:");
        getContentPane().add(lblCep);
        lblCep.setBounds(100, 250, 60, 40);

        lblComple.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblComple.setText("Comple:");
        getContentPane().add(lblComple);
        lblComple.setBounds(100, 300, 80, 40);
        getContentPane().add(txtCelular);
        txtCelular.setBounds(200, 410, 230, 22);
        getContentPane().add(txtNome);
        txtNome.setBounds(200, 110, 230, 22);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(200, 160, 230, 22);
        getContentPane().add(txtRua);
        txtRua.setBounds(200, 210, 230, 22);
        getContentPane().add(txtCep);
        txtCep.setBounds(200, 260, 230, 22);
        getContentPane().add(txtComple);
        txtComple.setBounds(200, 310, 230, 22);

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumero.setText("Número:");
        getContentPane().add(lblNumero);
        lblNumero.setBounds(100, 350, 80, 40);
        getContentPane().add(txtNumero);
        txtNumero.setBounds(200, 360, 230, 22);

        btnCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("CADASTRAR");
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(210, 470, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Assets\\logo.jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 180, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Assets\\fundovermelho.jpeg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 570, 80);

        setSize(new java.awt.Dimension(586, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblComple;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtComple;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
