/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vitor
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        btnCarrinho = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Assets\\logo.jpeg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 10, 180, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Assets\\fundovermelho.jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 80);

        btnPerfil.setBackground(new java.awt.Color(0, 0, 0));
        btnPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("PERFIL");
        getContentPane().add(btnPerfil);
        btnPerfil.setBounds(30, 100, 150, 40);

        btnCarrinho.setBackground(new java.awt.Color(0, 0, 0));
        btnCarrinho.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho.setText("CARRINHO");
        getContentPane().add(btnCarrinho);
        btnCarrinho.setBounds(590, 100, 150, 40);

        btnPedido.setBackground(new java.awt.Color(0, 0, 0));
        btnPedido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnPedido.setText("PEDIDOS");
        getContentPane().add(btnPedido);
        btnPedido.setBounds(310, 100, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-calabresa-catupiry.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 220, 96, 100);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("BEBIDAS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 750, 90, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-mista.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 340, 96, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-atum.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 220, 97, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-brocolis.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 220, 95, 100);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-calabresa.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(490, 220, 95, 100);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-alho.png")); // NOI18N
        jLabel9.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel9ComponentAdded(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 220, 96, 100);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-catupiry.png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 340, 96, 100);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-portuguesa.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 460, 96, 100);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-escarola.png")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 340, 96, 100);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-frango-catupiry.png")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(490, 340, 96, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-doisqueijos.png")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(190, 340, 96, 100);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-romeu-julieta.png")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 630, 97, 100);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("PIZZAS SALGADAS");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(300, 170, 170, 22);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-mussarela.png")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(270, 460, 96, 100);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Bebidas\\cocacola.jpeg")); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(100, 810, 100, 100);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("PIZZAS DOCES");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(330, 580, 140, 22);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Pizzas\\pizza-chocolate.png")); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(270, 630, 95, 100);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Bebidas\\sprite.png")); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(610, 810, 100, 100);

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Bebidas\\guarana.png")); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(270, 810, 100, 100);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor\\OneDrive\\Documentos\\NetBeansProjects\\projetopizzatime\\src\\Bebidas\\pepsi.jpeg")); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(440, 810, 110, 100);

        setSize(new java.awt.Dimension(787, 1087));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel9ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
